// Copyright (C) 2026 Toit contributors.
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.

import expect show *
import http

import openapi-runtime show OpenapiObject
import openapi-runtime.params show *

/**
Tests the parameter serialization styles of the OpenAPI specification.

The expected strings follow the "Style Examples" table of the OpenAPI
  specification, using the values `color="blue"`, `color=["blue", "black",
  "brown"]` and `color={"R": 100, "G": 200}`.
*/
main:
  test-query-param
  test-form
  test-delimited
  test-deep-object
  test-simple
  test-matrix
  test-label
  test-path-encoding
  test-header

/** A model class, as generated by the OpenAPI generator. */
class Color implements OpenapiObject:
  to-json -> Map:
    return {"R": 100, "G": 200}

expect-params expected/List actual/List:
  expect-equals expected.size actual.size
  expected.size.repeat: | i/int |
    param/QueryParam := actual[i]
    expect-equals expected[i] param.stringify

test-query-param:
  param := QueryParam "color" "blue"
  expect-equals "color=blue" param.stringify
  expect-equals "color=blue" param.url-encode
  // Non-string primitives are stringified before URL-encoding.
  expect-equals "limit=5" (QueryParam "limit" 5).url-encode
  expect-equals "flag=true" (QueryParam "flag" true).url-encode
  // Reserved characters are percent-encoded.
  expect-equals "a%20key=b%2Fvalue" (QueryParam "a key" "b/value").url-encode

test-form:
  // Primitives pass through unchanged.
  expect-params ["color=blue"] (encode-query-param "color" "blue")
  expect-params ["limit=5"] (encode-query-param "limit" 5)
  expect-params ["flag=true"] (encode-query-param "flag" true)

  // Arrays are joined with commas, or exploded into one param per item.
  expect-params ["color=blue,black,brown"]
      (encode-query-param "color" ["blue", "black", "brown"])
  expect-params ["ok=true,false"] (encode-query-param "ok" [true, false])
  expect-params ["color=blue", "color=black", "color=brown"]
      (encode-query-param "color" ["blue", "black", "brown"] --explode)

  // Objects are flattened to key,value pairs, or exploded into one param
  // per entry.
  expect-params ["color=R,100,G,200"]
      (encode-query-param "color" {"R": 100, "G": 200})
  expect-params ["R=100", "G=200"]
      (encode-query-param "color" {"R": 100, "G": 200} --explode)

  // Model classes are encoded through their JSON representation.
  expect-params ["color=R,100,G,200"] (encode-query-param "color" Color)

test-delimited:
  expect-params ["color=blue black brown"]
      (encode-query-param "color" ["blue", "black", "brown"] --style="spaceDelimited")
  expect-params ["color=blue|black|brown"]
      (encode-query-param "color" ["blue", "black", "brown"] --style="pipeDelimited")
  expect-params ["ok=true|false"]
      (encode-query-param "ok" [true, false] --style="pipeDelimited")
  expect-params ["color=R 100 G 200"]
      (encode-query-param "color" {"R": 100, "G": 200} --style="spaceDelimited")

test-deep-object:
  expect-params ["color[R]=100", "color[G]=200"]
      (encode-query-param "color" {"R": 100, "G": 200} --style="deepObject" --explode)
  expect-throw "UNIMPLEMENTED":
    encode-query-param "color" {"R": 100} --style="deepObject"

test-simple:
  expect-equals "blue" (encode-path-param "color" "blue")
  expect-equals "5" (encode-path-param "id" 5)
  expect-equals "true" (encode-path-param "flag" true)
  expect-equals "blue,black,brown"
      (encode-path-param "color" ["blue", "black", "brown"])
  expect-equals "R,100,G,200"
      (encode-path-param "color" {"R": 100, "G": 200})
  expect-equals "R=100,G=200"
      (encode-path-param "color" {"R": 100, "G": 200} --explode)

test-matrix:
  expect-equals ";color=blue" (encode-path-param "color" "blue" --style="matrix")
  expect-equals ";flag=true" (encode-path-param "flag" true --style="matrix")
  expect-equals ";color=blue,black,brown"
      (encode-path-param "color" ["blue", "black", "brown"] --style="matrix")
  expect-equals ";color=blue;color=black;color=brown"
      (encode-path-param "color" ["blue", "black", "brown"] --style="matrix" --explode)
  expect-equals ";color=R,100,G,200"
      (encode-path-param "color" {"R": 100, "G": 200} --style="matrix")
  expect-equals ";R=100;G=200"
      (encode-path-param "color" {"R": 100, "G": 200} --style="matrix" --explode)
  // A null value renders as the bare key.
  expect-equals ";color" (encode-path-param "color" null --style="matrix")

test-label:
  expect-equals ".blue" (encode-path-param "color" "blue" --style="label")
  expect-equals ".blue.black.brown"
      (encode-path-param "color" ["blue", "black", "brown"] --style="label")
  expect-equals ".blue.black.brown"
      (encode-path-param "color" ["blue", "black", "brown"] --style="label" --explode)
  expect-equals ".R.100.G.200"
      (encode-path-param "color" {"R": 100, "G": 200} --style="label")
  expect-equals ".R=100.G=200"
      (encode-path-param "color" {"R": 100, "G": 200} --style="label" --explode)
  // A null value renders as the bare label prefix.
  expect-equals "." (encode-path-param "color" null --style="label")

test-path-encoding:
  // Path-parameter values are percent-encoded by default so the result can
  // be substituted into a path segment verbatim.
  expect-equals "a%20b" (encode-path-param "p" "a b")
  expect-equals "a%2Fb" (encode-path-param "p" "a/b")
  expect-equals "a%2Cb,c" (encode-path-param "p" ["a,b", "c"])
  expect-equals "k%3Dx=v%26w" (encode-path-param "p" {"k=x": "v&w"} --explode)
  expect-equals ";color=a%3Bb" (encode-path-param "color" "a;b" --style="matrix")
  expect-equals ".a%20b" (encode-path-param "color" "a b" --style="label")
  // The style separators themselves are not encoded.
  expect-equals ";color=a%20b;color=c" (encode-path-param "color" ["a b", "c"] --style="matrix" --explode)
  // Encoding can be turned off.
  expect-equals "a b" (encode-path-param "p" "a b" --no-url-encode)

test-header:
  headers := http.Headers
  encode-header-param headers "X-Color" ["blue", "black"]
  expect-equals "blue,black" (headers.single "X-Color")
  encode-header-param headers "X-Flag" true
  expect-equals "true" (headers.single "X-Flag")
